app/models.py
from app.database import db

from flask_login import UserMixin
from app import login, bcrypt_hash


class User(db.Model, UserMixin):
    """ User database model and password functions """
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password_hash = db.Column(db.String(128), index=True, unique=True)

    def set_password(self, password):
        self.password_hash = bcrypt_hash.generate_password_hash(password).decode('utf-8')

    def check_password(self, password):
        return bcrypt_hash.check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User {}>'.format(self.username)


@login.user_loader
def load_user(id):
    """ Function for getting user by ID """
    return User.query.get(int(id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, EqualTo


class ChangePasswordForm(FlaskForm):
    """ Form for changing user password """
    old_password = PasswordField('Old password', validators=[DataRequired()])
    new_password1 = PasswordField('New password', validators=[DataRequired()])
    new_password2 = PasswordField('Repeat new password', validators=[DataRequired(), EqualTo('new_password1')])

    submit = SubmitField('Change password')

app/__init__.py
from flask import Flask
from config import Config

from flask_bcrypt import Bcrypt
from flask_login import LoginManager

from app.database import db
from flask_migrate import Migrate

from flask_bootstrap import Bootstrap

bcrypt_hash = Bcrypt()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = 'Log in to access this page.'
bootstrap = Bootstrap()


def create_app(config_class=Config):
    """ Create and initialize app """
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)  # initialize database
    login.init_app(app)  # initialize login library
    bcrypt_hash.init_app(app)  # initialize hashing library
    migrate.init_app(app, db)  # initialize db migration library
    bootstrap.init_app(app)  # initialize the main app

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app


from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, send_file, flash
from app.main import bp

from flask_login import login_required, current_user
from app.models import User
from app.main.forms import ChangePasswordForm, ChangeGitLabURIForm
from app.directory_scan import set_metadata, get_sample_by_id, get_artefact_by_id, get_tool_by_name
from flask import Markup
import yaml


@bp.route('/')
@bp.route('/index')
@login_required
def index():
    """ Dashboard """
    metadata = set_metadata()
    return render_template('index.html', title='Dashboard', metadata=metadata)


@bp.route('/user/<username>', methods=['GET', 'POST'])
@login_required
def user(username):
    """ User page, used for changing user password """
    account = User.query.filter_by(username=username).first_or_404()

    form = ChangePasswordForm()
    form2 = ChangeGitLabURIForm()
    form2.uri_to_gitlab.data = 'http://127.0.0.1:5002'
    if form.validate_on_submit():
        flash('Password changed')

    if form2.validate_on_submit():
        flash('Path to GitLab changed')

    return render_template('user.html', title='User settings', user=account, form=form, form2=form2)


@bp.route('/samples')
@login_required
def samples():
    """ Page listing all samples in environment """
    metadata = set_metadata()
    return render_template('samples.html', metadata=metadata)


@bp.route('/samples/<sample_id>')
@login_required
def sample(sample_id):
    """ Page for single samples """
    metadata = set_metadata()

    sample, data = get_sample_by_id(metadata['samples'], sample_id)

    return render_template('sample.html', sample=sample, data=data)

@bp.route('/samples/<sample_id>/download')
@login_required
def sample_download(sample_id):
    """ Downloading samples to local system """
    metadata = set_metadata()
    try:
        sample, data = get_sample_by_id(metadata['samples'], sample_id)
        sample_path = data['file_path'].split('/', 1)[1:][0]
    except TypeError:
        pass
    try:
        return send_file(sample_path, as_attachment=True)
    except Exception as e:
        print(e)


@bp.route('/results')
@login_required
def results():
    """ Page for all the results (artefacts and reports) found in environment """
    metadata = set_metadata()
    return render_template('results.html', metadata=metadata)


@bp.route('/samples/<sample_id>/results/<tool_name>/<artefact_id>')
@login_required
def result(sample_id, tool_name, artefact_id):
    """ Page for single results (artefacts and reports) """
    metadata = set_metadata()

    sample, data = get_sample_by_id(metadata['samples'], sample_id)
    artefacts = data['tools'][tool_name]['artefacts']

    artefact = get_artefact_by_id(artefacts, artefact_id)

    return render_template('result.html', artefact=artefact, sample=sample, sample_id=sample_id, tool=tool_name)


@bp.route('/samples/<sample_id>/results/<tool_name>/<artefact_id>/download')
@login_required
def result_download(sample_id, tool_name, artefact_id):
    """ Downloading results to local system """
    metadata = set_metadata()
    try:
        sample, data = get_sample_by_id(metadata['samples'], sample_id)
        artefacts = data['tools'][tool_name]['artefacts']

        artefact = get_artefact_by_id(artefacts, artefact_id)
        artefact_path = artefact['path'].split('/', 1)[1:][0]
        print(artefact_path)
    except TypeError:
        pass
    try:
        return send_file(artefact_path, as_attachment=True)
    except Exception as e:
        print(e)


@bp.route('/tools')
@login_required
def tools():
    """ Page for all the tools (tool scripts and pipelines) found in environment """
    metadata = set_metadata()
    return render_template('tools.html', metadata=metadata)


@bp.route('/tools/<tool_name>')
@login_required
def tool(tool_name):
    """ Page for single tools """
    metadata = set_metadata()
    tool = get_tool_by_name(metadata['available_tools'], tool_name)
    artefacts = {}

    for sample, data in metadata['samples'].items():
        try:
            artefacts[sample] = {'sample_id': data['id'], 'artefacts': data['tools'][tool_name]['artefacts']}
        except KeyError:
            pass

    return render_template('tool.html', tool=tool, metadata=metadata, artefacts=artefacts)

@bp.route('/pipelines/<pipeline_name>')
@login_required
def pipeline(pipeline_name):
    """ Page for single pipelines """
    metadata = set_metadata()['pipelines'][pipeline_name]

    pipeline_yaml = yaml.load("".join(metadata['contents']), Loader=yaml.SafeLoader)

    """render = '<p><div class="container"><div class="row">'
    job_count = len(pipeline_yaml['jobs'])
    columns = job_count * 2 + 1
    print("columns: ", 12 / columns)
    for i, job in enumerate(pipeline_yaml['jobs']):
        input = job['plan'][0]['get']
        task = job['plan'][1]['task']
        output = job['plan'][2]['put']
        render += '<div class="panel panel-default panel-warning col-sm-1">{}</div>'.format(input)
        render += '<div class="col-sm-1"><span class="glyphicon glyphicon-arrow-right"></span></div>'
        render += '<div class="panel panel-default panel-info col-sm-1">{}</div>'.format(task)
        render += '<div class="col-sm-1"><span class="glyphicon glyphicon-arrow-right"></span></div>'
        if i == len(pipeline_yaml['jobs'])-1:
            render += '<div class="panel panel-default panel-warning col-sm-1">{}</div>'.format(output)

    render = Markup(render)"""

    return render_template('pipeline.html', metadata=metadata, pipeline_name=pipeline_name) #, render=render)

app/workspace/pipelines/volatility-cortex-pipeline/workspace/tools/volatility/python-tools/plugins/__init__.py
from connections import *
from dll import *
from kdbgscan import *
from procdump import *
from process_memory import *
from psxview import *
from util import *

app/workspace/pipelines/volatility-pipeline-1/workspace/python-tools/plugins/__init__.py
__all__ = ["connections",
           "consoles",
           "dlldump",
           "dumpcerts",
           "kdbgscan",
           "procdump",
           "processmemory",
           "psxview",
           "util",
           "processmemory",
           "psxview",
           "util",
           "yarascan"]

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
      {% if title %}
      {{ title }} - CinCan
      {% else %}
      CinCan
      {% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for('main.index') }}">CinCan</a>
            </div>

            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('main.index') }}">Dashboard</a></li>
                    <li><a href="{{ url_for('main.samples') }}">Samples</a></li>
                    <li><a href="{{ url_for('main.results') }}">Results</a></li>
                    <li><a href="{{ url_for('main.tools') }}">Tools</a></li>

                    {% if current_user.is_anonymous %}
                        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    {% else %}
                        <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    {% endif %}
                </ul>

            </div>
            </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

    {% block app_content %}{% endblock %}

    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <a href="samples"><h3>Samples</h3></a>
                <div class="panel-group">
                {% for sample, data in metadata['samples'].items() %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="sample{{ data['id'] }}">
                                <a href="{{ url_for('main.sample', sample_id=data['id']) }}">
                                    <h4 class="panel-title">{{ sample }}</h4>
                                </a>
                                <p>results:  {{ data['log_count'] }} logs, {{ data['artefact_count'] }} artefacts<br />
                                size:  {{ data['file_size'] }} - last modified {{ data['modified'] }}</p>

                            </div>

                        </div>
                        {% endfor %}
                </div>
                <a href="results"><h3>Results</h3></a>
                <div class="panel-group">
                {% for sample, data in metadata['samples'].items() %}
                    {% for tool, tool_data in data['tools'].items() %}
                        {% for artefact in tool_data['artefacts'] %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab">
                                <a href="{{ url_for('main.result', sample_id=data['id'], tool_name=tool, artefact_id=artefact['id']) }}">
                                    <h4 class="panel-title">{{ artefact['filename'] }}</h4>
                                </a>
                                <p>source:  {{ sample }}</p>
                                <p>size:  {{ artefact['filesize'] }} - last modified {{ artefact['modified'] }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    {% endfor %}
                {% endfor %}
            </div>
            </div>
            <div class="col-sm-5">
                <a href="tools"><h3>Tools</h3></a>
                <div class="panel-group">
                    {% for tool, data in metadata['available_tools'].items() %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="sample{{ data['id'] }}">
                                <a href="{{ url_for('main.tool', tool_name=tool) }}">
                                    <h4 class="panel-title">{{ tool }}</h4>
                                </a>
                                <p>last updated: {{ data['updated'] }}</p>

                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a href="tools"><h3>Pipelines</h3></a>
                <div class="panel-group">
                    {% for pipeline, data in metadata['pipelines'].items() %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="sample{{ data['id'] }}">
                                <a href="{{ url_for('main.pipeline', pipeline_name=pipeline) }}">
                                    <h4 class="panel-title">{{ pipeline }}</h4>
                                </a>
                                <p>last updated: {{ data['modified'] }}</p>

                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

    </div>
</div>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Sign In</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/pipeline.html
{% extends "base.html" %}

{% block content %}
<div class="container w-75 pagination-centered">
    <div class="row justify-content-center">
        {{ render }}
    </div>

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>{{ pipeline_name }}</h3>
            </div>
            <div class="panel-body">
                {% if metadata['contents'] != None %}
                    <div style="border: 1px solid black; padding: 0.5em; margin: 0.5em;">
                        {% for line in metadata['contents'] %}
                            {{ line }}<br />
                        {% endfor %}
                    </div>
                {% endif %}

            </div>

        </div>
    </div>
</div>


{% endblock %}

app/templates/result.html
{% extends "base.html" %}

{% block content %}
<div class="container w-75">

    <div class="panel panel-default">
        <div class="panel-heading">

            <h4 class="panel-title">{{ artefact['filename'] }}</h4>
            <a class="btn btn-primary"
                href="{{ url_for('main.result_download', sample_id=sample_id, tool_name=tool, artefact_id=artefact['id']) }}"
                role="button">Download</a>

            <p>source:  {{ sample }}</p>
            <p>size:  {{ artefact['filesize'] }} - last modified {{ artefact['modified'] }}</p>
         </div>
        <div class="panel-body">

            <p>tool: <a href="{{ url_for('main.tool', tool_name=tool) }}">{{ tool }}</a></p>
            <p>source:  <a href="{{ url_for('main.sample', sample_id=sample_id) }}">{{ sample }}</a></p>
            <p>size:  {{ artefact['filesize'] }} - last modified {{ artefact['modified'] }}</p>
            <p>path: {{ artefact['path'] }}</p>
            <p>MIME: {{ artefact['MIME'] }}</p>
            {% if artefact['contents'] != None %}
                <div style="border: 1px solid black; padding: 0.5em; margin: 0.5em;">
                    {% for line in artefact['contents'] %}
                        {{ line }}<br />
                    {% endfor %}
                </div>
            {% endif %}

        </div>


    </div>

</div>
{% endblock %}

app/templates/results.html
{% extends "base.html" %}


{% block app_content %}
    <h3>Results</h3>
    <div class="row">
        <div class="panel-group col-sm-8" id="accordion" role="tablist" aria-multiselectable="true">
            {% for sample, data in metadata['samples'].items() %}
                {% for tool, tool_data in data['tools'].items() %}
                    {% for artefact in tool_data['artefacts'] %}
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="artefact{{ data['id'] }}_{{ tool_data['id'] }}_{{ artefact['id'] }}">
                            <a href="{{ url_for('main.result', sample_id=data['id'], tool_name=tool, artefact_id=artefact['id']) }}">
                                <h4 class="panel-title">{{ artefact['filename'] }}</h4>
                            </a>
                            <a class="btn btn-primary pull-right"
                                href="{{ url_for('main.result_download', sample_id=data["id"], tool_name=tool, artefact_id=artefact['id']) }}"
                                role="button">Download</a>
                            <p>source:  {{ sample }}</p>
                            <p>size:  {{ artefact['filesize'] }} - last modified {{ artefact['modified'] }}</p>
                                <button class="btn btn-primary"
                                        role="button"
                                        data-toggle="collapse"
                                        data-parent="#accordion"
                                        href="#preview{{ data['id'] }}_{{ tool_data['id'] }}_{{ artefact['id'] }}"
                                        id="btn{{ data['id'] }}_{{ tool_data['id'] }}_{{ artefact['id'] }}">Preview</button>


                        </div>

                        <div class="panel-collapse collapse"
                             role="tabpanel"
                             aria-labelledby="sample{{ data['id'] }}"
                             id="preview{{ data['id'] }}_{{ tool_data['id'] }}_{{ artefact['id'] }}">
                             <div class="panel-heading">
                                <div class="panel-body">

                                <p>tool: {{ tool }}</p>
                                <p>source:  {{ sample }}</p>
                                <p>size:  {{ artefact['filesize'] }} - last modified {{ artefact['modified'] }}</p>
                                <p>path: {{ artefact['path'] }}</p>
                                <p>MIME: {{ artefact['MIME'] }}</p>
                                {% if artefact['contents'] != None %}
                                    <div style="border: 1px solid black; padding: 0.5em; margin: 0.5em;">
                                        {% for line in artefact['contents'] %}
                                            {{ line }}<br />
                                        {% endfor %}
                                    </div>
                                {% endif %}

                                </div>
                             </div>
                        </div>
                    </div>
                    {% endfor %}
                {% endfor %}
            {% endfor %}
        </div>
    </div>


{% endblock %}

app/templates/sample.html
{% extends "base.html" %}

{% block content %}
<div class="container w-75">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>{{ sample }}</h3>
            <a class="btn btn-primary"
                href="{{ url_for('main.sample_download', sample_id=data['id']) }}"
                role="button">Download</a>
            <div class="panel-body">
                {% for tool, tool_data in data['tools'].items() %}
                    <a href="{{ url_for('main.tool', tool_name=tool) }}"><h4>{{ tool }}</h4></a>

                    {% for artefact in tool_data['artefacts'] %}
                        <div style="border: 1px solid black; padding: 0.5em; margin: 0.5em;">
                            <a href="{{ url_for('main.result', sample_id=data['id'], tool_name=tool, artefact_id=artefact['id']) }}">
                                <h4 class="panel-title">{{ artefact['filename'] }}</h4>
                            </a>
                            <p>source: {{ sample }}</p>
                            <p>size:  {{ artefact['filesize'] }} - last modified {{ artefact['modified'] }}</p>
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
</div>
</div>

{% endblock %}

app/templates/samples.html
{% extends "base.html" %}


{% block app_content %}
    <h3>Samples</h3>
    <div class="row">
        <div class="panel-group col-sm-8" id="accordion" role="tablist" aria-multiselectable="true">
            {% for sample, data in metadata['samples'].items() %}
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="sample{{ data['id'] }}">
                        <a href="{{ url_for('main.sample', sample_id=data['id']) }}">
                            <h4 class="panel-title">{{ sample }}</h4>
                        </a>
                            <a class="btn btn-primary pull-right"
                                href="{{ url_for('main.sample_download', sample_id=data['id']) }}"
                                role="button">Download</a>
                        <p>results:  {{ data['log_count'] }} logs, {{ data['artefact_count'] }} artefacts</p>
                        <p>size:  {{ data['file_size'] }} - last modified {{ data['modified'] }}</p>
                        {% if data['tools']|length > 0 %}
                            <button class="btn btn-primary"
                                    role="button"
                                    data-toggle="collapse"
                                    data-parent="#accordion"
                                    href="#preview{{ data['id'] }}"
                                    id="btn{{ data['id'] }}">Preview</button>
                        {% endif %}
                    </div>

                    <div class="panel-collapse collapse"
                         role="tabpanel"
                         aria-labelledby="sample{{ data['id'] }}"
                         id="preview{{ data['id'] }}">
                         <div class="panel-heading">
                            <div class="panel-body">
                                    {% for tool, tool_data in data['tools'].items() %}
                                        <h4>{{ tool }}</h4>
                                        <p>results:</p>
                                        {% for artefact in tool_data['artefacts'] %}
                                            <div style="border: 1px solid black; padding: 0.5em; margin: 0.5em;">
                                                <a href="{{ url_for('main.result', sample_id=data['id'], tool_name=tool, artefact_id=artefact['id']) }}">
                                                    <h4 class="panel-title">{{ artefact['filename'] }}</h4>
                                                </a>
                                                <p>source:  {{ sample }}</p>
                                                <p>size:  {{ artefact['filesize'] }} - last modified {{ artefact['modified'] }}</p>
                                            </div>
                                        {% endfor %}
                                    {% endfor %}
                            </div>
                         </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}

app/templates/tool.html
{% extends "base.html" %}

{% block content %}
<div class="container w-75">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>{{ tool['name'] }}</h3>
            <div class="panel-body">

                    <p>results:</p>
                    {% for sample, data in artefacts.items() %}
                        {% for artefact in data['artefacts'] %}
                            <div style="border: 1px solid black; padding: 0.5em; margin: 0.5em;">
                                <a href="{{ url_for('main.result', sample_id=data['sample_id'], tool_name=tool['name'], artefact_id=artefact['id']) }}">
                                    <h4 class="panel-title">{{ artefact['filename'] }}</h4>
                                </a>
                                <p>source:  <a href="{{ url_for('main.sample', sample_id=data['sample_id']) }}">{{ sample }}</a></p>
                                <p>size:  {{ artefact['filesize'] }} - last modified {{ artefact['modified'] }}</p>
                            </div>
                        {% endfor %}

                    {% endfor %}
            </div>
        </div>
    </div>
    </div>

{% endblock %}

app/templates/tools.html
{% extends "base.html" %}


{% block app_content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <h3>Tools</h3>
                <div class="panel-group">
                    {% for tool, data in metadata['available_tools'].items() %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="sample{{ data['id'] }}">
                                <a href="{{ url_for('main.tool', tool_name=tool) }}">
                                    <h4 class="panel-title">{{ tool }}</h4>
                                </a>
                                <p>last updated: {{ data['updated'] }}</p>

                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-sm-5">
                <h3>Pipelines</h3>
                <div class="panel-group">
                    {% for pipeline, data in metadata['pipelines'].items() %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="sample{{ data['id'] }}">
                                <a href="{{ url_for('main.pipeline', pipeline_name=pipeline) }}">
                                    <h4 class="panel-title">{{ pipeline }}</h4>
                                </a>
                                <p>last updated: {{ data['modified'] }}</p>

                            </div>
                        </div>
                    {% endfor %}
                </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/user.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container w-75 pagination-centered">
    <h3>Change password</h3>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</div>
{% endblock %}